# Generated by Django 3.2.9 on 2021-11-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='paid_for_class',
        ),
        migrations.AlterField(
            model_name='register',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('staff', 'staff')], default='customer', max_length=20),
        ),
    ]
