# Generated by Django 3.2.9 on 2021-11-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basic_color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('white', 'white'), ('blue', 'blue'), ('wooden', 'wooden'), ('black', 'black'), ('yellow', 'yellow'), ('orange', 'orange')], default='wooden', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='foam',
            field=models.CharField(blank=True, choices=[('PU foam', 'PU foam'), ('rubber foam', 'rubber foam')], default='PU foam', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(blank=True, choices=[('cloth', 'cloth'), ('rexine', 'rexine'), ('leather', 'leather')], default='leather', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='warrenty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wood_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('sofa', 'sofa'), ('bed', 'bed'), ('shelves', 'shelves'), ('chair', 'chair'), ('table', 'table')], default='sofa', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
