# Generated by Django 3.2.6 on 2022-01-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_advancepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
