# Generated by Django 3.2.6 on 2022-01-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='seller',
        ),
    ]
