# Generated by Django 3.2.6 on 2022-01-10 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='delivered_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='packed_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='shipped_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
